### PR TITLE
Address some nits

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Still WIP...
- [ ] Allow app to scan for Travis and RS at the same time
- [ ] Move `services` to `optionalServices` as these services are not broadcasted but cached once connected.
- [ ] Get notified of battery changes
- [ ] Add handshake (not sure why...)

### CODE REVIEW

**Comment by poshaughnessy** [comment]
Thanks for this! I'll just take a quick look once I'm home and I expect to merge it this evening.

**Comment by poshaughnessy** [comment]
I've tried a few times, but I haven't managed to get the drone to take off, since pulling your changes. It appears to write the command OK, but the drone isn't responding... Is it working for you? 

I'll take a more thorough look at this tomorrow / over the weekend!

**Comment by beaufortfrancois** [comment]
This doesn't fix it yet sadly.
This PR is just a WIP of what can be improved for now ;(

I'm still trying to understand what is going on....

**Comment by beaufortfrancois** [comment]
Here's a trace of adb commands that succeed:

```
8.872191          Data: 04 01 00 04 01 00 32 30 31 36 2d 30 38 2d 30 35 00
8.953378          Data: 04 02 00 04 02 00 54 31 33 33 34 32 31 2b 30 32 30 30 00  
9.030102          Data: 04 05 00 02 00 00
9.656882          Data: 04 06 00 04 00 00
9.795046          Data: 04 07 02 0e 01 00 62 75 6c 6c 68 65 61 64 00
9.865389          Data: 04 0a 02 0e 00 00 4e 65 78 75 73 20 35 58 00

15.903287         Data: 04 0b 00 08 00 00 01

19.647837         Data: 04 0c 02 00 01 00
19.687011         Data: 04 0d 02 0d 00 00 36 12 57 84 51 70 48 40
19.732982         Data: 04 0e 02 0d 01 00 e4 3b e7 5d ab a3 02 40

22.451516         Data: 04 0f 02 00 03 00
```

I'm not sure why the step jumps of 3...
Ack bytes are different...

I still don't get it. I'm not sure it is Web Bluetooth fault there ;(

**Comment by beaufortfrancois** [comment]
@poshaughnessy Did you have some time to have a look at it?

**Comment by poshaughnessy** [comment]
@beaufortfrancois Just taking a look now. Sorry I didn't sooner (funny timing though, I was literally just looking again anyway when I saw your message 3 mins ago!)

**Comment by poshaughnessy** [comment]
@beaufortfrancois Please may I ask how you chose the bytes to send for the commands you changed? E.g. For the 'land' command I see you have updated bytes 3-5 from [2, 0, 3] to [0, 4, 0]?

I have been pretty blind to the Parrot API so far - I haven't been able to find proper docs for it yet, although I'm still trying: https://github.com/voodootikigod/node-rolling-spider/issues/78. I've basically just been following the node-rolling-spider code as a working example so far.

There is a little bit of info here though: 
http://forum.developer.parrot.com/t/bluetooth-attribute-definitions-for-roll-pitch-yaw-rotation-and-altitude/105/5 
http://forum.developer.parrot.com/t/minimal-ble-commands-to-send-for-take-off/1686/3

Have you found anything else yourself?
- Ah looks like you're tracing the Android app...

I think I'll return to the node-rolling-spider commands just for now. I'm going to add forwards/backwards/left/right, then I'll check on the take-off command again and see if I can get it working more consistently. I'll dig out my BLE sniffer when I can find it as that may help!

**Comment by poshaughnessy** [comment]
@beaufortfrancois Do you fancy giving the latest in `master` (published at https://webdr.one) a try when you get a chance?

I was making a lot of changes so I've pulled in most of your changes manually. It seems to be working pretty well for me at the moment. I've added forwards/backwards/left/right controls. I think the 'ping' that I added is helping to keep the connection open with the drone. 

The drone has been ignoring my commands sometimes but I think that is explained by it having been low on battery. (It seems like < 10% and it will silently ignore). 

I'll do some more testing and I need to fix up so you can use it multiple times without refreshing the page to reset, but hopefully it's pretty close otherwise... 

Thanks again for helping with this!

**Comment by beaufortfrancois** [comment]
Just tried it and it works great now! WoW! It is really cool ;)

**Comment by beaufortfrancois** [comment]
I still stumble upon some issues some times but it definitely happens less.
I'm not sure why.

**Comment by poshaughnessy** [comment]
Thanks and apologies I didn't merge your PR to show your contribution in Github, but I added a credit to the README!

Yeah I think it's working a lot better. Sometimes it still seems to take a couple of goes. I'll do some more testing and hope to release a v1.2 with some more fixes soon :)

**Pull request closed without merging**
